# @package _group_
kwargs:
  gpus: 1
  accelerator: dp
  max_epochs: 20
  gradient_clip_val: 1
  limit_train_batches: 25000000
  log_every_n_steps: 100
  precision: 32
  terminate_on_nan: False
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 2
  replace_sampler_ddp: False
checkpoint_kwargs:
  verbose: True
  save_top_k: 5
  save_last: True
  monitor: val_ssim_fid100_f1_total_mean
  mode: max