indir: /content/CAIR/test_images/input #input image path
outdir: /content/CAIR/test_images/output #output path

model:
  path: /content/CAIR/checkpoint # path for checkpoint folder
  checkpoint: last.ckpt

dataset:
  kind: img_with_mask


device: cuda
out_key: predicted_image
